### ISSUE TITLE
Koodikatselmointi 1

### ISSUE THREAD

**Issue by anttilip** [pidrmasiin/omahahelp#1]
*Ladattu 19.11 klo 21:00*

# Koodikatselmointi 1

Ohjelman rakenne ei suoraan oikein auennut, joten korjaa ihmeessä,
jos ymmärsin jotain väärin. Ohjelman monimutkaisimpiin luokkiin ja metodeihin
kannattaa jättää kommentteja selkeyttämään niiden toimintaa.

Ymmärsin rakenteen näin:
Cards-paketissa Card-luokka esittää yhtä korttia. Cards-luokka esittää korttipakkaa
ja luokkaa käytetään uudelleen myös esittämään pelaajan kättä Values-luokassa.
PlayersHand-luokkaa käytetään esittämään pelaajan käsikortteja.

Compare-paketissa Values esittää yhtä mahdollista korttiyhdistelmää (kaksi käsikorttia
ja kolme pöytäkorttia). Values-luokka suorittaa korttiyhdistelmien vertailut,
esim parit, suorat, värit jne. HandsValues luokkaa käytetään Values-luokassa tallentamaan
korttiyhdistelmien samoja arvoja (esim kaksi kuningasta). Compare luokkaa ei käytetä
vielä mihinkään, mutta ilmeisesti vertailee kahden pelaajan käsikorttien vahvuutta.

Deal-paketissa Draw-luokka arpoo kortteja ja suorittaa pöytäkorttien jaon.

Itse pelin kulun logiikka tulee Mainiin.

-------------------------------------------------------------
Hyvää projektissa on se, että luokkia on useita, luokat eivät ole paisunut liian suuriksi
ja metodit toteuttavat vain yksittäisen asian. Jos metodit suorittavat monimutkaisia
tehtäviä, esimerkiksi Values-luokan `checkSames`-metodi, käytetään muita metodeita
jakamaan onglema pienempiin osiin.

### Ehdotuksia

Ensimmäisenä silmään pisti Card-luokka, joka esittää kortin maan ja numeroarvon kokonaislukuina.
Suosittelisin, että ainakin kortin maa esitetään kokonaisluvun sijaan enum arvona.
Pelikortit ovat yksi yleisimmistä esimerkeistä, jossa voidaan käytää enum-luokkia intuitiivisesti.

Enum-luokkien käytöstä pelikorttien esittämiseen löytyy tarkempaa kuvausta esimerkiksi [ohjelmoinnin moocin materiaalista (luku 58.2)](http://2016-ohjelmointi.mooc.fi/viikko13/) tai [java 5 enum tutoriaalista](http://docs.oracle.com/javase/1.5.0/docs/guide/language/enums.html).
Enumien hyötyinä on selkeä ja helppolukuinen koodi, sekä ymmärrettävä tulostus, esimerkiksi:
```Java
Card kortti = new Card(Rank.ACE, Suit.SPADES);
System.out.println(kortti);

>> ACE of SPADES
```

Cards luokka jäi hämmentämään, sillä sitä käytetään kahteen eri tarkoitukseen.
Mielestäni olisi kannattavaa jakaa luokka käyttötarkoitusta vastaaviin erillisiin luokkiin.
Esimerkiksi korttipakkaa kuvaava Deck.java, pöytää kuvaava Board.java ja pelaajan kättä
kuvaava luokka PlayersHand, joka projektista jo löytyykin.

Lisäksi Cards-luokan `addCards()`-metodi on turhan monimutkainen. Yksi kätevä tapa on käyttää
kahta sisäkkäistä foreach-looppia, esimerkiksi näin:
```pseudo
For each suit in Suits
    For each rank in Ranks:
        Add new Card(suit, rank) to Cards
    End of loop
End of loop
```
Foreach-loopit selkeyttävät koodia verrattuna while-looppiin, jossa käytetään
useita eri kokonaislukuja pitämään lukua korttien maista ja arvoista.
Samaa tapaa kannattaa käyttää muuallakin projektissa, esimerkiksi Values-luokassa.

Values-luokka siis vertailee eri korttiyhdistelmien vahvuuksia. Itse tekeisin
vertailun Analyzer-luokassa, jossa olisi staattisia metodeita, esimerkiksi
`evaluateHand()`, joka saa parametrina pelaajan käden, korttipakan ja pöydän.
Metodi palauttaisi jonkun numeerisen arvion käden vahvuudesta. Lisäksi luokassa
voisi olla muita julkisia metodeita, esimerkiksi `probabilityForFlush()`, joka
perustuu pelaan käteen ja pöydällä oleviin kortteihin.

Aiheen määrittelyssä sanotaan, että ohjelman tarkoitus on laskea todennäköisyys
voitolle, mutta ohjelma ei vielä taida sisältää todennäköisyyksien laskentaa.
Todennäköisyyksiä voidaan arvioida simuloimalla useita eri pöytäkortteja tai
laskea ihan todennäköisyysmatikalla. Käsien vahvuuksien arviointi silti lienee helpompaa.

Jos itse tekisin vastaavan ohjelman, jakaisin logiikan seuraaviin luokkiin

**Omaha.java**
- Pitää sisällään pelin kulkua vastaavan logiikan
- Luo pakan
- Ohjelman käyttäjä asettaa kortit pakasta pelaajien käsiin
- Pyytää Analyzer-luokkaa vertailemaan käsien vahvuus ennen floppia
- Ohjelman käyttäjä asettaa pöytään koritit, jotka tulivat flopissa
- Vertailee käsien vahvuuden flopin jälkeen

**Deck.java**
- Kuvaa pakkaa (nykyinen Cards)

**Card.java**
- Esittää yhtä korttia
- Käyttää ainakin kortin maan kuvaamiseen Enumerator luokkaa

**PlayersHand.java**
- Kuvaa pelaajan neljää käsikorttia

**Board.java**
- Kuvaa pöytään tulleita kortteja

**Analyzer.java**
- Public `compareHand`-metodi, joka saa parametrina pelaajan käden, pöydän ja mahdollisesti myös pakan
- compareHand-metodi palauttaa luvun, joka kuvaa käden vahvuutta
- Useita private apumetodeita käden vahvuuden tarkastamiseen

Omaha.javan rakenne pelaajien käsien vahvuuksien arvioinnissa:
```Java
Deck deck = new Deck();
deck.generateCards();

// Pyydä ohjelman käyttäjältä jaossa saadut omat kortit
// OwnCards kuvaa saatuja korteja
for (Card card : ownCards) {
    player1.addCard(card);
    deck.remove(card);
}

// Pyydä ohjelman käyttäjältä arvatut vastustajan kortit
// OpponentsCards kuvaa arvattuja vastustajan kortteja
for (Card card : opponentsCards) {
    player2.addCard(card);
    deck.remove(card);
}

// Pyydä Analyzer.javalta pelaajien käsien vahvuuksien arviot
int player1HandStrength =  Analyzer.evaluateHand(player1, board, deck);
int player2HandStrength =  Analyzer.evaluateHand(player2, board, deck);

System.out.println("Pelaajan 1 käden vahvuus: " + player1HandStrength);
System.out.println("Pelaajan 2 käden vahvuus: " + player2HandStrength);

// Pyydä käyttäjältä flopin korit, lisää ne pöytään ja analysoi pelaajien kädet uudelleen
// Toista turnin ja riverin korteilla
```

Nämä ovat vain ehdotuksia, eivätkä välttämättä ole järkevin tapa toteuttaa ohjelmaa.
Itselle vain ohjelman rakenne ei tuntunut intuitiiviselta, mutta en olekaan koskaan tehnyt
vastaavaa ohjelmaa.

Jos ymmärsin jotain aivan väärin, ehdotuksistani jäi jotain epäselväksi tai haluat
kysyä jotain niin kommentoi alle niin voin tarkentaa palautettani.

Terveisin,
Antti Lipsanen

**Comment by pidrmasiin** [comment]
Olipas hyvää palautetta ja neuvoja! Kiitos!
